export const words = [
  { word: "about", hint: "Relates to a topic." },
  { word: "account", hint: "Record of events or finances." },
  { word: "across", hint: "From one side to another." },
  { word: "addition", hint: "Act of combining." },
  { word: "after", hint: "Following in time." },
  { word: "again", hint: "Repeated action." },
  { word: "against", hint: "In opposition." },
  { word: "agreement", hint: "Mutual understanding." },
  { word: "almost", hint: "Nearly but not fully." },
  { word: "among", hint: "In a group." },
  { word: "amount", hint: "Quantity of something." },
  { word: "amusement", hint: "Fun or entertainment." },
  { word: "angle", hint: "Space between lines." },
  { word: "angry", hint: "Feeling of displeasure." },
  { word: "animal", hint: "Non-plant living creature." },
  { word: "answer", hint: "Reply to a question." },
  { word: "apparatus", hint: "Equipment for a task." },
  { word: "apple", hint: "Common tree fruit." },
  { word: "approval", hint: "Acceptance or agreement." },
  { word: "argument", hint: "Dispute or reasoning." },
  { word: "attack", hint: "Sudden aggression." },
  { word: "attempt", hint: "Effort to achieve." },
  { word: "attention", hint: "Focus or notice." },
  { word: "authority", hint: "Power or control." },
  { word: "automatic", hint: "Self-operating." },
  { word: "awake", hint: "Not asleep." },
  { word: "balance", hint: "Stability or equality." },
  { word: "basin", hint: "Shallow liquid container." },
  { word: "basket", hint: "Woven carrying container." },
  { word: "beautiful", hint: "Visually pleasing." },
  { word: "because", hint: "Reason or cause." },
  { word: "before", hint: "Earlier in time." },
  { word: "behaviour", hint: "Way someone acts." },
  { word: "belief", hint: "Acceptance as true." },
  { word: "berry", hint: "Small juicy fruit." },
  { word: "between", hint: "Among two or more." },
  { word: "birth", hint: "Act of being born." },
  { word: "bitter", hint: "Sharp, unpleasant taste." },
  { word: "black", hint: "Color without light." },
  { word: "blade", hint: "Cutting edge of tool." },
  { word: "blood", hint: "Red bodily fluid." },
  { word: "board", hint: "Flat piece of wood." },
  { word: "boiling", hint: "Liquid at vapor point." },
  { word: "bottle", hint: "Liquid container." },
  { word: "brain", hint: "Organ of thought." },
  { word: "brake", hint: "Device to stop motion." },
  { word: "branch", hint: "Tree or system extension." },
  { word: "brass", hint: "Yellowish metal alloy." },
  { word: "bread", hint: "Food from flour." },
  { word: "breath", hint: "Inhaled and exhaled air." },
  { word: "brick", hint: "Construction block." },
  { word: "bridge", hint: "Structure over obstacle." },
  { word: "bright", hint: "Full of light." },
  { word: "broken", hint: "Damaged or in pieces." },
  { word: "brother", hint: "Male sibling." },
  { word: "brown", hint: "Earthy color." },
  { word: "brush", hint: "Bristled cleaning tool." },
  { word: "bucket", hint: "Carrying container." },
  { word: "building", hint: "Constructed structure." },
  { word: "burst", hint: "Sudden break open." },
  { word: "business", hint: "Commercial activity." },
  { word: "butter", hint: "Spread from cream." },
  { word: "button", hint: "Small fastener." },
  { word: "camera", hint: "Image-capturing device." },
  { word: "canvas", hint: "Woven fabric for art." },
  { word: "carriage", hint: "Vehicle or train part." },
  { word: "cause", hint: "Reason for event." },
  { word: "certain", hint: "Sure without doubt." },
  { word: "chain", hint: "Connected links." },
  { word: "chalk", hint: "White writing substance." },
  { word: "chance", hint: "Possibility or opportunity." },
  { word: "change", hint: "Make different." },
  { word: "cheap", hint: "Low in cost." },
  { word: "cheese", hint: "Food from milk." },
  { word: "chemical", hint: "Distinct substance." },
  { word: "chest", hint: "Body part or box." },
  { word: "chief", hint: "Leader or main." },
  { word: "church", hint: "Religious building." },
  { word: "circle", hint: "Round shape." },
  { word: "clean", hint: "Free from dirt." },
  { word: "clear", hint: "Transparent or obvious." },
  { word: "clock", hint: "Time-measuring device." },
  { word: "cloth", hint: "Woven fabric." },
  { word: "cloud", hint: "Water vapor mass." },
  { word: "collar", hint: "Neck band." },
  { word: "colour", hint: "Visual light property." },
  { word: "comfort", hint: "State of ease." },
  { word: "committee", hint: "Task-assigned group." },
  { word: "common", hint: "Ordinary or shared." },
  { word: "company", hint: "Business or group." },
  { word: "complete", hint: "Finished or whole." },
  { word: "complex", hint: "Intricate or complicated." },
  { word: "condition", hint: "State or circumstance." },
  { word: "conscious", hint: "Aware or awake." },
  { word: "control", hint: "Power to regulate." },
  { word: "copper", hint: "Reddish-brown metal." },
  { word: "cotton", hint: "Soft plant fiber." },
  { word: "cough", hint: "Air expulsion from lungs." },
  { word: "country", hint: "Nation or rural area." },
  { word: "cover", hint: "Protect or conceal." },
  { word: "crack", hint: "Narrow break." },
  { word: "credit", hint: "Recognition or loan." },
  { word: "crime", hint: "Illegal act." },
  { word: "cruel", hint: "Causing pain." },
  { word: "crush", hint: "Squeeze with force." },
  { word: "current", hint: "Happening now." },
  { word: "curtain", hint: "Window-covering fabric." },
  { word: "curve", hint: "Bending line." },
  { word: "cushion", hint: "Soft comfort pad." },
  { word: "damage", hint: "Harm or injury." },
  { word: "danger", hint: "Risk of harm." },
  { word: "daughter", hint: "Female child." },
  { word: "death", hint: "End of life." },
  { word: "decision", hint: "Choice or judgment." },
  { word: "degree", hint: "Unit of measure." },
  { word: "delicate", hint: "Fine or fragile." },
  { word: "dependent", hint: "Relies on another." },
  { word: "design", hint: "Plan or creation." },
  { word: "desire", hint: "Strong wish." },
  { word: "detail", hint: "Small particular." },
  { word: "different", hint: "Not the same." },
  { word: "digestion", hint: "Food breakdown process." },
  { word: "direction", hint: "Guidance or course." },
  { word: "dirty", hint: "Unclean or soiled." },
  { word: "discovery", hint: "Finding something new." },
  { word: "disease", hint: "Illness or disorder." },
  { word: "disgust", hint: "Strong disapproval." },
  { word: "distance", hint: "Space between points." },
  { word: "division", hint: "Act of separating." },
  { word: "doubt", hint: "Uncertainty or disbelief." },
  { word: "drain", hint: "Remove liquid." },
  { word: "drawer", hint: "Sliding storage." },
  { word: "dress", hint: "Garment or clothe." },
  { word: "drink", hint: "Consume liquid." },
  { word: "driving", hint: "Operating a vehicle." },
  { word: "early", hint: "Before expected time." },
  { word: "earth", hint: "Planet or soil." },
  { word: "education", hint: "Learning or teaching." },
  { word: "effect", hint: "Result of action." },
  { word: "elastic", hint: "Stretchy material." },
  { word: "electric", hint: "Powered by electricity." },
  { word: "engine", hint: "Energy-to-motion machine." },
  { word: "enough", hint: "Sufficient amount." },
  { word: "equal", hint: "Same in value." },
  { word: "error", hint: "Mistake or inaccuracy." },
  { word: "event", hint: "Significant occurrence." },
  { word: "every", hint: "All in a group." },
  { word: "example", hint: "Sample or illustration." },
  { word: "exchange", hint: "Trade or swap." },
  { word: "existence", hint: "State of being." },
  { word: "expansion", hint: "Act of growing." },
  { word: "expert", hint: "Highly skilled person." },
  { word: "false", hint: "Not true." },
  { word: "family", hint: "Related group." },
  { word: "father", hint: "Male parent." },
  { word: "feather", hint: "Bird's plumage." },
  { word: "feeble", hint: "Weak or frail." },
  { word: "feeling", hint: "Emotion or sensation." },
  { word: "female", hint: "Of feminine gender." },
  { word: "fertile", hint: "Able to produce." },
  { word: "fiction", hint: "Imaginary story." },
  { word: "field", hint: "Open land or area." },
  { word: "fight", hint: "Conflict or struggle." },
  { word: "finger", hint: "Digit on hand." },
  { word: "first", hint: "Initial in order." },
  { word: "fixed", hint: "Set or repaired." },
  { word: "flame", hint: "Burning gas." },
  { word: "flight", hint: "Act of flying." },
  { word: "floor", hint: "Surface of room." },
  { word: "flower", hint: "Blooming plant." },
  { word: "foolish", hint: "Lacking sense." },
  { word: "force", hint: "Strength or power." },
  { word: "forward", hint: "Ahead in direction." },
  { word: "frame", hint: "Structure or border." },
  { word: "frequent", hint: "Happening often." },
  { word: "friend", hint: "Close companion." },
  { word: "front", hint: "Foremost part." },
  { word: "fruit", hint: "Edible plant produce." },
  { word: "future", hint: "Time to come." },
  { word: "garden", hint: "Planted outdoor space." },
  { word: "general", hint: "Broad or common." },
  { word: "glass", hint: "Transparent material." },
  { word: "glove", hint: "Hand covering." },
  { word: "grain", hint: "Small particle or cereal." },
  { word: "grass", hint: "Green ground cover." },
  { word: "great", hint: "Very large or excellent." },
  { word: "green", hint: "Emerald color." },
  { word: "group", hint: "Collection of items." },
  { word: "growth", hint: "Process of increasing." },
  { word: "guide", hint: "Lead or direct." },
  { word: "hammer", hint: "Striking tool." },
  { word: "hanging", hint: "Suspended state." },
  { word: "happy", hint: "Feeling joy." },
  { word: "harbour", hint: "Sheltered port." },
  { word: "harmony", hint: "Pleasing unity." },
  { word: "healthy", hint: "In good condition." },
  { word: "hearing", hint: "Sense of sound." },
  { word: "heart", hint: "Vital organ or center." },
  { word: "history", hint: "Record of past." },
  { word: "hollow", hint: "Empty inside." },
  { word: "horse", hint: "Large riding animal." },
  { word: "hospital", hint: "Medical facility." },
  { word: "house", hint: "Residential building." },
  { word: "humour", hint: "Amusing quality." },
  { word: "important", hint: "Of great value." },
  { word: "impulse", hint: "Sudden urge." },
  { word: "increase", hint: "Grow in amount." },
  { word: "industry", hint: "Manufacturing or trade." },
  { word: "insect", hint: "Small six-legged creature." },
  { word: "insurance", hint: "Risk protection." },
  { word: "interest", hint: "Curiosity or concern." },
  { word: "invention", hint: "New creation." },
  { word: "island", hint: "Land surrounded by water." },
  { word: "jelly", hint: "Soft, gelatinous food." },
  { word: "jewel", hint: "Precious stone." },
  { word: "journey", hint: "Travel or trip." },
  { word: "judge", hint: "Decide or evaluate." },
  { word: "kettle", hint: "Water-boiling vessel." },
  { word: "knife", hint: "Cutting tool." },
  { word: "knowledge", hint: "Information or understanding." },
  { word: "language", hint: "System of communication." },
  { word: "laugh", hint: "Express amusement." },
  { word: "learning", hint: "Acquiring knowledge." },
  { word: "leather", hint: "Tanned animal hide." },
  { word: "letter", hint: "Written message or character." },
  { word: "level", hint: "Flat or equal position." },
  { word: "library", hint: "Book collection." },
  { word: "light", hint: "Illumination or brightness." },
  { word: "limit", hint: "Boundary or restriction." },
  { word: "linen", hint: "Flax-based fabric." },
  { word: "liquid", hint: "Flowing substance." },
  { word: "little", hint: "Small in size." },
  { word: "living", hint: "Alive or residing." },
  { word: "loose", hint: "Not tight." },
  { word: "machine", hint: "Mechanical device." },
  { word: "manager", hint: "Person in charge." },
  { word: "market", hint: "Place for trade." },
  { word: "married", hint: "Wedded state." },
  { word: "match", hint: "Pair or ignite." },
  { word: "material", hint: "Substance or fabric." },
  { word: "measure", hint: "Determine size or amount." },
  { word: "medical", hint: "Related to health." },
  { word: "meeting", hint: "Gathering of people." },
  { word: "memory", hint: "Recollection or storage." },
  { word: "metal", hint: "Hard, shiny substance." },
  { word: "middle", hint: "Central position." },
  { word: "military", hint: "Related to armed forces." },
  { word: "minute", hint: "Small or time unit." },
  { word: "mixed", hint: "Combined or varied." },
  { word: "money", hint: "Currency for trade." },
  { word: "monkey", hint: "Primate animal." },
  { word: "month", hint: "Calendar division." },
  { word: "morning", hint: "Early part of day." },
  { word: "mother", hint: "Female parent." },
  { word: "motion", hint: "Act of moving." },
  { word: "mountain", hint: "High landmass." },
  { word: "mouth", hint: "Opening for eating." },
  { word: "muscle", hint: "Body tissue for movement." },
  { word: "music", hint: "Art of sound." },
  { word: "narrow", hint: "Slim or restricted." },
  { word: "nation", hint: "Country or people." },
  { word: "natural", hint: "From nature." },
  { word: "necessary", hint: "Required or essential." },
  { word: "needle", hint: "Sharp sewing tool." },
  { word: "nerve", hint: "Body signal carrier." },
  { word: "night", hint: "Dark time period." },
  { word: "noise", hint: "Unwanted sound." },
  { word: "normal", hint: "Usual or typical." },
  { word: "north", hint: "Cardinal direction." },
  { word: "number", hint: "Count or quantity." },
  { word: "offer", hint: "Present or propose." },
  { word: "office", hint: "Workplace or position." },
  { word: "operation", hint: "Action or procedure." },
  { word: "opinion", hint: "Personal belief." },
  { word: "opposite", hint: "Contrary or facing." },
  { word: "orange", hint: "Citrus fruit or color." },
  { word: "order", hint: "Arrangement or command." },
  { word: "ornament", hint: "Decorative item." },
  { word: "other", hint: "Different or additional." },
  { word: "owner", hint: "Possessor of something." },
  { word: "paint", hint: "Colorful coating." },
  { word: "paper", hint: "Thin writing material." },
  { word: "parallel", hint: "Side-by-side lines." },
  { word: "parcel", hint: "Packaged item." },
  { word: "paste", hint: "Sticky substance." },
  { word: "payment", hint: "Money given." },
  { word: "peace", hint: "Calm or tranquility." },
  { word: "pencil", hint: "Writing tool." },
  { word: "person", hint: "Human individual." },
  { word: "physical", hint: "Related to body." },
  { word: "picture", hint: "Visual image." },
  { word: "place", hint: "Location or position." },
  { word: "plane", hint: "Flat surface or aircraft." },
  { word: "plant", hint: "Living organism or factory." },
  { word: "plate", hint: "Flat dish." },
  { word: "please", hint: "Polite request." },
  { word: "pleasure", hint: "Feeling of enjoyment." },
  { word: "plough", hint: "Farming tool." },
  { word: "pocket", hint: "Small storage space." },
  { word: "point", hint: "Tip or purpose." },
  { word: "poison", hint: "Harmful substance." },
  { word: "polish", hint: "Shine or refine." },
  { word: "political", hint: "Related to government." },
  { word: "porter", hint: "Luggage carrier." },
  { word: "position", hint: "Place or role." },
  { word: "possible", hint: "Able to occur." },
  { word: "potato", hint: "Starchy vegetable." },
  { word: "powder", hint: "Fine particles." },
  { word: "power", hint: "Strength or authority." },
  { word: "present", hint: "Gift or now." },
  { word: "price", hint: "Cost of item." },
  { word: "print", hint: "Reproduce text or image." },
  { word: "prison", hint: "Confinement facility." },
  { word: "private", hint: "Not public." },
  { word: "probable", hint: "Likely to happen." },
  { word: "process", hint: "Series of actions." },
  { word: "produce", hint: "Create or yield." },
  { word: "profit", hint: "Financial gain." },
  { word: "property", hint: "Owned item or land." },
  { word: "prose", hint: "Non-poetic writing." },
  { word: "protest", hint: "Express objection." },
  { word: "public", hint: "Open to all." },
  { word: "purpose", hint: "Reason or goal." },
  { word: "quality", hint: "Degree of excellence." },
  { word: "question", hint: "Inquiry or doubt." },
  { word: "quick", hint: "Fast or rapid." },
  { word: "quiet", hint: "Low noise." },
  { word: "quite", hint: "Completely or somewhat." },
  { word: "range", hint: "Extent or variety." },
  { word: "reaction", hint: "Response to stimulus." },
  { word: "reading", hint: "Act of interpreting text." },
  { word: "ready", hint: "Prepared for action." },
  { word: "reason", hint: "Cause or logic." },
  { word: "receipt", hint: "Proof of payment." },
  { word: "record", hint: "Document or log." },
  { word: "regret", hint: "Feeling of sorrow." },
  { word: "regular", hint: "Consistent or usual." },
  { word: "relation", hint: "Connection or kin." },
  { word: "religion", hint: "Belief system." },
  { word: "request", hint: "Ask for something." },
  { word: "respect", hint: "Admiration or regard." },
  { word: "reward", hint: "Benefit for action." },
  { word: "rhythm", hint: "Pattern of beats." },
  { word: "right", hint: "Correct or direction." },
  { word: "river", hint: "Large flowing water." },
  { word: "rough", hint: "Not smooth." },
  { word: "round", hint: "Circular shape." },
  { word: "scale", hint: "Measure or size." },
  { word: "school", hint: "Place for learning." },
  { word: "science", hint: "Study of nature." },
  { word: "scissors", hint: "Cutting tool." },
  { word: "screw", hint: "Fastening device." },
  { word: "second", hint: "Next or time unit." },
  { word: "secret", hint: "Hidden information." },
  { word: "secretary", hint: "Administrative assistant." },
  { word: "selection", hint: "Act of choosing." },
  { word: "sense", hint: "Perception or meaning." },
  { word: "separate", hint: "Divide or distinct." },
  { word: "serious", hint: "Important or grave." },
  { word: "servant", hint: "Person who serves." },
  { word: "shade", hint: "Shadow or color." },
  { word: "shake", hint: "Vibrate or tremble." },
  { word: "shame", hint: "Feeling of guilt." },
  { word: "sharp", hint: "Pointed or keen." },
  { word: "sheep", hint: "Woolly animal." },
  { word: "shelf", hint: "Storage surface." },
  { word: "shirt", hint: "Upper body garment." },
  { word: "shock", hint: "Sudden surprise." },
  { word: "short", hint: "Brief or small." },
  { word: "silver", hint: "Shiny metal." },
  { word: "simple", hint: "Easy or plain." },
  { word: "sister", hint: "Female sibling." },
  { word: "skirt", hint: "Lower body garment." },
  { word: "sleep", hint: "Restful state." },
  { word: "slope", hint: "Inclined surface." },
  { word: "small", hint: "Little in size." },
  { word: "smash", hint: "Break violently." },
  { word: "smell", hint: "Sense of odor." },
  { word: "smile", hint: "Happy expression." },
  { word: "smoke", hint: "Vapor from burning." },
  { word: "smooth", hint: "Even surface." },
  { word: "snake", hint: "Legless reptile." },
  { word: "sneeze", hint: "Sudden air expulsion." },
  { word: "society", hint: "Group of people." },
  { word: "solid", hint: "Firm substance." },
  { word: "sound", hint: "Audible vibration." },
  { word: "south", hint: "Cardinal direction." },
  { word: "space", hint: "Area or gap." },
  { word: "spade", hint: "Digging tool." },
  { word: "special", hint: "Unique or important." },
  { word: "sponge", hint: "Absorbent material." },
  { word: "spoon", hint: "Eating utensil." },
  { word: "spring", hint: "Season or coil." },
  { word: "square", hint: "Four-sided shape." },
  { word: "stage", hint: "Platform or phase." },
  { word: "stamp", hint: "Mark or postage." },
  { word: "start", hint: "Begin something." },
  { word: "statement", hint: "Expressed fact." },
  { word: "station", hint: "Place or post." },
  { word: "steam", hint: "Water vapor." },
  { word: "steel", hint: "Strong metal alloy." },
  { word: "stick", hint: "Thin piece or adhere." },
  { word: "sticky", hint: "Adhesive surface." },
  { word: "stiff", hint: "Rigid or firm." },
  { word: "still", hint: "Motionless or yet." },
  { word: "stitch", hint: "Sewing loop." },
  { word: "stocking", hint: "Foot covering." },
  { word: "stomach", hint: "Digestive organ." },
  { word: "stone", hint: "Hard rock." },
  { word: "store", hint: "Shop or stockpile." },
  { word: "story", hint: "Narrative or tale." },
  { word: "straight", hint: "Not curved." },
  { word: "strange", hint: "Unusual or odd." },
  { word: "street", hint: "Public road." },
  { word: "stretch", hint: "Extend or expand." },
  { word: "strong", hint: "Powerful or sturdy." },
  { word: "structure", hint: "Built form." },
  { word: "substance", hint: "Material or essence." },
  { word: "sudden", hint: "Quick and unexpected." },
  { word: "sugar", hint: "Sweet substance." },
  { word: "summer", hint: "Warm season." },
  { word: "support", hint: "Aid or hold up." },
  { word: "surprise", hint: "Unexpected event." },
  { word: "sweet", hint: "Sugary taste." },
  { word: "system", hint: "Organized method." },
  { word: "table", hint: "Flat furniture." },
  { word: "taste", hint: "Flavor sensation." },
  { word: "teaching", hint: "Imparting knowledge." },
  { word: "tendency", hint: "Inclination or trend." },
  { word: "theory", hint: "Explanation or idea." },
  { word: "there", hint: "In that place." },
  { word: "thick", hint: "Wide or dense." },
  { word: "thing", hint: "Object or item." },
  { word: "thought", hint: "Mental idea." },
  { word: "thread", hint: "Thin strand." },
  { word: "throat", hint: "Passage for food." },
  { word: "through", hint: "Passing across." },
  { word: "thumb", hint: "Short finger." },
  { word: "thunder", hint: "Storm sound." },
  { word: "ticket", hint: "Entry pass." },
  { word: "tight", hint: "Firmly fixed." },
  { word: "tired", hint: "Feeling exhausted." },
  { word: "together", hint: "In unity." },
  { word: "tomorrow", hint: "Next day." },
  { word: "tongue", hint: "Mouth organ." },
  { word: "tooth", hint: "Hard mouth structure." },
  { word: "touch", hint: "Physical contact." },
  { word: "trade", hint: "Exchange of goods." },
  { word: "train", hint: "Vehicle or instruct." },
  { word: "transport", hint: "Move goods or people." },
  { word: "trick", hint: "Deceptive act." },
  { word: "trouble", hint: "Difficulty or problem." },
  { word: "trousers", hint: "Leg garment." },
  { word: "twist", hint: "Turn or distort." },
  { word: "umbrella", hint: "Rain protection." },
  { word: "under", hint: "Beneath or below." },
  { word: "value", hint: "Worth or importance." },
  { word: "verse", hint: "Poetry line." },
  { word: "vessel", hint: "Ship or container." },
  { word: "violent", hint: "Intense or forceful." },
  { word: "voice", hint: "Sound from speech." },
  { word: "waiting", hint: "Remaining in expectation." },
  { word: "waste", hint: "Unused or discarded." },
  { word: "watch", hint: "Timepiece or observe." },
  { word: "water", hint: "Clear liquid." },
  { word: "weather", hint: "Atmospheric condition." },
  { word: "weight", hint: "Mass or heaviness." },
  { word: "wheel", hint: "Circular motion device." },
  { word: "where", hint: "At what place." },
  { word: "while", hint: "During a time." },
  { word: "whistle", hint: "Shrill sound." },
  { word: "white", hint: "Pure color." },
  { word: "window", hint: "Glass opening." },
  { word: "winter", hint: "Cold season." },
  { word: "woman", hint: "Adult female." },
  { word: "wound", hint: "Injury or twist." },
  { word: "writing", hint: "Text creation." },
  { word: "wrong", hint: "Incorrect." },
  { word: "yellow", hint: "Bright color." },
  { word: "yesterday", hint: "Previous day." },
  { word: "young", hint: "Early in age." }
];